language: ruby
cache: bundler
bundler_args: --without tools
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - "[ -d coverage ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - jruby-9.2.7.0
env:
  global:
    - COVERAGE=true
    - JRUBY_OPTS='--dev -J-Xmx1024M'
notifications:
  email: false
