language: ruby
dist: trusty
cache: bundler
bundler_args: --without tools
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - jruby-9.2.6.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
addons:
  code_climate:
    repo_token: cec3ffbd851658b020e33353508235e82685c2dbea045147051437c956a79285
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
